"""Add Geolocation to items

Revision ID: 18ee44c097eb
Revises: c3c22277f560
Create Date: 2025-01-05 10:09:49.260655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18ee44c097eb"
down_revision: Union[str, None] = "c3c22277f560"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("longitude", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("latitude", sa.Float(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_item_latitude"), ["latitude"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_item_longitude"), ["longitude"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_longitude"))
        batch_op.drop_index(batch_op.f("ix_item_latitude"))
        batch_op.drop_column("latitude")
        batch_op.drop_column("longitude")

    # ### end Alembic commands ###
